package xyz.jphil.datahelper;

import com.google.auto.service.AutoService;
import com.palantir.javapoet.*;
import xyz.jphil.datahelper.processor.util.CodeGeneratorUtils;
import xyz.jphil.datahelper.processor.util.FieldAnalyzer;
import xyz.jphil.datahelper.processor.util.FieldInfo;
import xyz.jphil.datahelper.processor.util.ProcessorUtils;
import xyz.jphil.datahelper.processor.util.ProjectionGenerator;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Processor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;

/**
 * Annotation processor for {@code @Data} (no-Lombok path).
 *
 * <p>Generates the same {@code Foo_IR}/{@code Foo_I}/{@code Foo_R} projection as the
 * {@code @DataHelper} path (so both paths share one mental model), plus the sealed abstract
 * {@code Foo_A} base that the user class extends.</p>
 *
 * <p>{@code Foo_A implements Foo_I<Foo>} and only contributes the field-backed delegating
 * getters/setters and the {@code Object} methods ({@code equals}/{@code hashCode}/{@code toString});
 * the 15 property accessors, the fluent methods, and {@code toRecord()} are inherited as interface
 * defaults from {@code Foo_IR}/{@code Foo_I}. A static {@code Foo.from(Foo_R)} (inherited from
 * {@code Foo_A}) mirrors {@code record.toMutable()}.</p>
 *
 * <h3>Example Usage:</h3>
 * <pre>
 * {@code @Data}
 * public final class Person extends Person_A {
 *     String name;
 *     Integer age;
 * }
 * </pre>
 *
 * @see Data
 */
@AutoService(Processor.class)
@SupportedAnnotationTypes("xyz.jphil.datahelper.Data")
@SupportedSourceVersion(SourceVersion.RELEASE_21)
public class DataProcessor extends AbstractProcessor {

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        for (TypeElement annotation : annotations) {
            for (Element element : roundEnv.getElementsAnnotatedWith(annotation)) {
                if (element.getKind() == ElementKind.CLASS) {
                    processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE,
                            "Processing @Data on " + element);
                    generate((TypeElement) element);
                }
            }
        }
        return true;
    }

    private void generate(TypeElement element) {
        String packageName = processingEnv.getElementUtils().getPackageOf(element).toString();
        String className = element.getSimpleName().toString();

        ProcessorUtils utils = new ProcessorUtils(processingEnv);
        FieldAnalyzer analyzer = new FieldAnalyzer(processingEnv, utils);

        List<FieldInfo> fields = analyzer.analyzeFields(element);
        if (fields == null) {
            return; // Validation errors found
        }

        // Shared projection (no traits on the @Data path).
        TypeSpec ir = ProjectionGenerator.buildReadableInterface(packageName, className, fields, utils, List.of());
        TypeSpec i  = ProjectionGenerator.buildWritableInterface(packageName, className, fields, utils, List.of());
        TypeSpec r  = ProjectionGenerator.buildRecord(packageName, className, fields);
        TypeSpec a  = buildAbstractBase(packageName, className, fields);

        writeType(packageName, ir, className + "_IR");
        writeType(packageName, i,  className + "_I");
        writeType(packageName, r,  className + "_R");
        writeType(packageName, a,  className + "_A");
    }

    private TypeSpec buildAbstractBase(String packageName, String className, List<FieldInfo> fields) {
        ClassName concrete = ClassName.get(packageName, className);

        TypeSpec.Builder a = TypeSpec.classBuilder(className + "_A")
                .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT, Modifier.SEALED)
                .addPermittedSubclass(concrete)
                .addJavadoc("Sealed abstract base class for {@link $L} (generated by @Data).\n", className)
                .addJavadoc("\n<p>Implements the writable interface and delegates field access to the child;\n")
                .addJavadoc("property accessors, fluent methods and {@code toRecord()} are inherited as defaults.</p>\n")
                .addSuperinterface(ParameterizedTypeName.get(ClassName.get(packageName, className + "_I"), concrete));

        // 'sub' field for delegation (opposite of 'super')
        a.addField(FieldSpec.builder(concrete, "sub", Modifier.PRIVATE, Modifier.FINAL)
                .initializer("($T) this", concrete)
                .build());

        // Field-backed getters/setters; everything else is inherited from _IR/_I defaults.
        ProjectionGenerator.addDelegatingAccessors(a, fields);

        // Object methods (value-based) delegating to the DataHelper_I statics.
        a.addMethod(CodeGeneratorUtils.createEqualsMethod());
        a.addMethod(CodeGeneratorUtils.createHashCodeMethod());
        a.addMethod(CodeGeneratorUtils.createToStringMethod());

        // Static factory: Foo.from(Foo_R) -> Foo (inheritable through the subclass).
        a.addMethod(ProjectionGenerator.buildFromStatic(packageName, className));

        return a.build();
    }

    private void writeType(String packageName, TypeSpec type, String displayName) {
        JavaFile javaFile = JavaFile.builder(packageName, type)
                .indent("    ")
                .skipJavaLangImports(true)
                .addFileComment("Generated by DataProcessor on " + LocalDateTime.now())
                .build();
        try {
            javaFile.writeTo(processingEnv.getFiler());
            processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE, "Generated: " + displayName);
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR,
                    "Failed to generate " + displayName + ": " + e.getMessage());
        }
    }
}
